FROM apache/airflow:2.9.0

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    openjdk-17-jdk

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$PATH

USER airflow

RUN pip install \
    apache-airflow-providers-google \
    pandas \
    numpy \
    faker \
    dbt-bigquery \
    pyspark==3.5.1
