# FROM apache/airflow:2.9.0

FROM apache/airflow:2.9.0

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev

USER airflow

RUN pip install \
    apache-airflow-providers-google \
    nba_api \
    pandas \
    numpy